os: linux
sudo: required
language: cpp

addons:
    apt:
        update: true
        sources:
            - ubuntu-toolchain-r-test
            - deb http://archive.ubuntu.com/ubuntu/ bionic universe
        packages:
            - autoconf-archive
            - cpputest
            - g++-7

install: true

script:
  - ./autogen.sh
  - CC=gcc-7 CXX=g++-7 ./configure --enable-check
  - make check
