os: linux
# dist: trusty
# sudo: required
language: cpp

addons:
    apt:
        update: true
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - autoconf-archive
            - cpputest
            - g++-7

env:
    - CC=gcc-7
    - CXX=g++-7

install: true

script:
  - ./autogen.sh
  - ./configure --enable-check
  - make check
