dist: trusty
language: cpp
sudo: required

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - autoconf-archive
            - cpputest
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7 && CXXFLAGS=-std=gnu++1z"

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - ./autogen.sh

script:
  - ./configure --enable-check && make check
