os: linux
language: cpp

addons:
    apt:
        update: true
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - autoconf-archive
            - cpputest
            - g++-7

install: true

script:
  - ./autogen.sh
  - CC=gcc-7 CXX=g++-7 CXXFLAGS='-std=gnu++17' ./configure --enable-check
  - make check
