dist: trusty
language: cpp
sudo: required

before_install:
    - sudo add-apt-repository universe -y
    - sudo apt-get update -q
    - sudo apt-get install autoconf-archive -y

install:
  - ./autogen.sh

