os: linux
sudo: required
language: c
services:
- docker
script:
- docker build -t project .
after_success: |
  cd "$TRAVIS_BUILD_DIR"
  docker run project tar -c -O doc | tar -x
  pushd doc/html
  git init
  git checkout -b gh-pages
  git add .
  git -c user.name='travis' -c user.email='travis' commit -m init
  git push -f https://${GITHUB_API_KEY}@github.com/coolparadox/number-reducer gh-pages
  popd
