dist: trusty
language: cpp
sudo: required

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - universe
          packages:
            - g++-7
            - cpputest
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - ./autogen.sh

script:
  - ./configure --enable-check && make check
